/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import 'ionicons';


export namespace Components {

  interface AeIconsComponent {
    'color': string;
    'name': string;
    'size': string;
  }
  interface AeIconsComponentAttributes extends StencilHTMLAttributes {
    'color'?: string;
    'name'?: string;
    'size'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AeIconsComponent': Components.AeIconsComponent;
  }

  interface StencilIntrinsicElements {
    'ae-icons-component': Components.AeIconsComponentAttributes;
  }


  interface HTMLAeIconsComponentElement extends Components.AeIconsComponent, HTMLStencilElement {}
  var HTMLAeIconsComponentElement: {
    prototype: HTMLAeIconsComponentElement;
    new (): HTMLAeIconsComponentElement;
  };

  interface HTMLElementTagNameMap {
    'ae-icons-component': HTMLAeIconsComponentElement
  }

  interface ElementTagNameMap {
    'ae-icons-component': HTMLAeIconsComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
