/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AeIoniconsComponent {
    'color': string;
    'name': string;
    'size': string;
  }
  interface AeIoniconsComponentAttributes extends StencilHTMLAttributes {
    'color'?: string;
    'name'?: string;
    'size'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AeIoniconsComponent': Components.AeIoniconsComponent;
  }

  interface StencilIntrinsicElements {
    'ae-ionicons-component': Components.AeIoniconsComponentAttributes;
  }


  interface HTMLAeIoniconsComponentElement extends Components.AeIoniconsComponent, HTMLStencilElement {}
  var HTMLAeIoniconsComponentElement: {
    prototype: HTMLAeIoniconsComponentElement;
    new (): HTMLAeIoniconsComponentElement;
  };

  interface HTMLElementTagNameMap {
    'ae-ionicons-component': HTMLAeIoniconsComponentElement
  }

  interface ElementTagNameMap {
    'ae-ionicons-component': HTMLAeIoniconsComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
